// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package bitswap_message_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Wantlist             *Message_Wantlist  `protobuf:"bytes,1,opt,name=wantlist" json:"wantlist,omitempty"`
	Blocks               [][]byte           `protobuf:"bytes,2,rep,name=blocks" json:"blocks,omitempty"`
	Payload              []*Message_Block   `protobuf:"bytes,3,rep,name=payload" json:"payload,omitempty"`
	MessageType          *string            `protobuf:"bytes,4,opt,name=messageType" json:"messageType,omitempty"`
	Backup               *Message_Backup    `protobuf:"bytes,5,opt,name=backup" json:"backup,omitempty"`
	Links                []string           `protobuf:"bytes,6,rep,name=links" json:"links,omitempty"`
	Response             []byte             `protobuf:"bytes,7,opt,name=response" json:"response,omitempty"`
	FileHash             *string            `protobuf:"bytes,8,opt,name=fileHash" json:"fileHash,omitempty"`
	TagPacks             []*Message_Tagpack `protobuf:"bytes,9,rep,name=tagPacks" json:"tagPacks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (dst *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(dst, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetWantlist() *Message_Wantlist {
	if m != nil {
		return m.Wantlist
	}
	return nil
}

func (m *Message) GetBlocks() [][]byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Message) GetPayload() []*Message_Block {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetMessageType() string {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return ""
}

func (m *Message) GetBackup() *Message_Backup {
	if m != nil {
		return m.Backup
	}
	return nil
}

func (m *Message) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Message) GetResponse() []byte {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Message) GetFileHash() string {
	if m != nil && m.FileHash != nil {
		return *m.FileHash
	}
	return ""
}

func (m *Message) GetTagPacks() []*Message_Tagpack {
	if m != nil {
		return m.TagPacks
	}
	return nil
}

type Message_Wantlist struct {
	Entries              []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	Full                 *bool                     `protobuf:"varint,2,opt,name=full" json:"full,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Message_Wantlist) Reset()         { *m = Message_Wantlist{} }
func (m *Message_Wantlist) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist) ProtoMessage()    {}
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0, 0}
}
func (m *Message_Wantlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist.Unmarshal(m, b)
}
func (m *Message_Wantlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist.Marshal(b, m, deterministic)
}
func (dst *Message_Wantlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist.Merge(dst, src)
}
func (m *Message_Wantlist) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist.Size(m)
}
func (m *Message_Wantlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist proto.InternalMessageInfo

func (m *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Message_Wantlist) GetFull() bool {
	if m != nil && m.Full != nil {
		return *m.Full
	}
	return false
}

type Message_Wantlist_Entry struct {
	Block                *string  `protobuf:"bytes,1,opt,name=block" json:"block,omitempty"`
	Priority             *int32   `protobuf:"varint,2,opt,name=priority" json:"priority,omitempty"`
	Operation            *int32   `protobuf:"varint,3,opt,name=operation" json:"operation,omitempty"`
	SettleSlice          []byte   `protobuf:"bytes,4,opt,name=settleSlice" json:"settleSlice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Wantlist_Entry) Reset()         { *m = Message_Wantlist_Entry{} }
func (m *Message_Wantlist_Entry) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist_Entry) ProtoMessage()    {}
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0, 0, 0}
}
func (m *Message_Wantlist_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist_Entry.Unmarshal(m, b)
}
func (m *Message_Wantlist_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist_Entry.Marshal(b, m, deterministic)
}
func (dst *Message_Wantlist_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist_Entry.Merge(dst, src)
}
func (m *Message_Wantlist_Entry) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist_Entry.Size(m)
}
func (m *Message_Wantlist_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist_Entry proto.InternalMessageInfo

func (m *Message_Wantlist_Entry) GetBlock() string {
	if m != nil && m.Block != nil {
		return *m.Block
	}
	return ""
}

func (m *Message_Wantlist_Entry) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *Message_Wantlist_Entry) GetOperation() int32 {
	if m != nil && m.Operation != nil {
		return *m.Operation
	}
	return 0
}

func (m *Message_Wantlist_Entry) GetSettleSlice() []byte {
	if m != nil {
		return m.SettleSlice
	}
	return nil
}

type Message_Block struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Block) Reset()         { *m = Message_Block{} }
func (m *Message_Block) String() string { return proto.CompactTextString(m) }
func (*Message_Block) ProtoMessage()    {}
func (*Message_Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0, 1}
}
func (m *Message_Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Block.Unmarshal(m, b)
}
func (m *Message_Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Block.Marshal(b, m, deterministic)
}
func (dst *Message_Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Block.Merge(dst, src)
}
func (m *Message_Block) XXX_Size() int {
	return xxx_messageInfo_Message_Block.Size(m)
}
func (m *Message_Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Block proto.InternalMessageInfo

func (m *Message_Block) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Message_Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message_Backup struct {
	Copynum              *int32   `protobuf:"varint,1,opt,name=copynum" json:"copynum,omitempty"`
	Nodelist             []string `protobuf:"bytes,2,rep,name=nodelist" json:"nodelist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Backup) Reset()         { *m = Message_Backup{} }
func (m *Message_Backup) String() string { return proto.CompactTextString(m) }
func (*Message_Backup) ProtoMessage()    {}
func (*Message_Backup) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0, 2}
}
func (m *Message_Backup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Backup.Unmarshal(m, b)
}
func (m *Message_Backup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Backup.Marshal(b, m, deterministic)
}
func (dst *Message_Backup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Backup.Merge(dst, src)
}
func (m *Message_Backup) XXX_Size() int {
	return xxx_messageInfo_Message_Backup.Size(m)
}
func (m *Message_Backup) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Backup.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Backup proto.InternalMessageInfo

func (m *Message_Backup) GetCopynum() int32 {
	if m != nil && m.Copynum != nil {
		return *m.Copynum
	}
	return 0
}

func (m *Message_Backup) GetNodelist() []string {
	if m != nil {
		return m.Nodelist
	}
	return nil
}

type Message_Tagpack struct {
	Index                *int32   `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Hash                 *string  `protobuf:"bytes,2,opt,name=hash" json:"hash,omitempty"`
	Tag                  []byte   `protobuf:"bytes,3,opt,name=tag" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Tagpack) Reset()         { *m = Message_Tagpack{} }
func (m *Message_Tagpack) String() string { return proto.CompactTextString(m) }
func (*Message_Tagpack) ProtoMessage()    {}
func (*Message_Tagpack) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_51fa334063160aaf, []int{0, 3}
}
func (m *Message_Tagpack) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Tagpack.Unmarshal(m, b)
}
func (m *Message_Tagpack) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Tagpack.Marshal(b, m, deterministic)
}
func (dst *Message_Tagpack) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Tagpack.Merge(dst, src)
}
func (m *Message_Tagpack) XXX_Size() int {
	return xxx_messageInfo_Message_Tagpack.Size(m)
}
func (m *Message_Tagpack) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Tagpack.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Tagpack proto.InternalMessageInfo

func (m *Message_Tagpack) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *Message_Tagpack) GetHash() string {
	if m != nil && m.Hash != nil {
		return *m.Hash
	}
	return ""
}

func (m *Message_Tagpack) GetTag() []byte {
	if m != nil {
		return m.Tag
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "bitswap.message.pb.Message")
	proto.RegisterType((*Message_Wantlist)(nil), "bitswap.message.pb.Message.Wantlist")
	proto.RegisterType((*Message_Wantlist_Entry)(nil), "bitswap.message.pb.Message.Wantlist.Entry")
	proto.RegisterType((*Message_Block)(nil), "bitswap.message.pb.Message.Block")
	proto.RegisterType((*Message_Backup)(nil), "bitswap.message.pb.Message.Backup")
	proto.RegisterType((*Message_Tagpack)(nil), "bitswap.message.pb.Message.Tagpack")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_51fa334063160aaf) }

var fileDescriptor_message_51fa334063160aaf = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x8a, 0xd4, 0x40,
	0x10, 0xc6, 0xc9, 0x64, 0xf3, 0xaf, 0x26, 0x82, 0x34, 0x22, 0x4d, 0xf0, 0x10, 0x57, 0x0f, 0xc1,
	0x43, 0x0e, 0xeb, 0x4d, 0x41, 0x45, 0x5c, 0xf0, 0x22, 0x48, 0xb9, 0xe0, 0xb9, 0x27, 0xd3, 0x33,
	0xdb, 0x4c, 0xb6, 0xbb, 0x49, 0xf7, 0xb0, 0x9b, 0x67, 0xf2, 0xa1, 0x7c, 0x15, 0xe9, 0x4a, 0x26,
	0x2e, 0x08, 0x83, 0xb7, 0xfa, 0x55, 0xd7, 0xd7, 0x5d, 0x55, 0x5f, 0xc3, 0x93, 0x3b, 0xe9, 0x9c,
	0xd8, 0xcb, 0xd6, 0x0e, 0xc6, 0x1b, 0xc6, 0x36, 0xca, 0xbb, 0x7b, 0x61, 0xdb, 0x25, 0xbd, 0xb9,
	0xfc, 0x95, 0x42, 0xf6, 0x6d, 0x42, 0xf6, 0x09, 0xf2, 0x7b, 0xa1, 0x7d, 0xaf, 0x9c, 0xe7, 0x51,
	0x1d, 0x35, 0xeb, 0xab, 0xd7, 0xed, 0xbf, 0x92, 0x76, 0x2e, 0x6f, 0x7f, 0xce, 0xb5, 0xb8, 0xa8,
	0xd8, 0x73, 0x48, 0x37, 0xbd, 0xe9, 0x0e, 0x8e, 0xaf, 0xea, 0xb8, 0x29, 0x71, 0x26, 0xf6, 0x1e,
	0x32, 0x2b, 0xc6, 0xde, 0x88, 0x2d, 0x8f, 0xeb, 0xb8, 0x59, 0x5f, 0xbd, 0x3c, 0x77, 0xf1, 0xe7,
	0x20, 0xc2, 0x93, 0x82, 0xd5, 0xb0, 0x9e, 0x8b, 0x6e, 0x46, 0x2b, 0xf9, 0x45, 0x1d, 0x35, 0x05,
	0x3e, 0x4e, 0xb1, 0x77, 0x90, 0x6e, 0x44, 0x77, 0x38, 0x5a, 0x9e, 0x50, 0xdb, 0x97, 0x67, 0x6f,
	0xa7, 0x4a, 0x9c, 0x15, 0xec, 0x19, 0x24, 0xbd, 0xd2, 0x07, 0xc7, 0xd3, 0x3a, 0x6e, 0x0a, 0x9c,
	0x80, 0x55, 0x90, 0x0f, 0xd2, 0x59, 0xa3, 0x9d, 0xe4, 0x59, 0x1d, 0x35, 0x25, 0x2e, 0x1c, 0xce,
	0x76, 0xaa, 0x97, 0x5f, 0x85, 0xbb, 0xe5, 0x39, 0x35, 0xb3, 0x30, 0xfb, 0x08, 0xb9, 0x17, 0xfb,
	0xef, 0x22, 0xac, 0xa0, 0xa0, 0x49, 0x5f, 0x9d, 0xeb, 0xe5, 0x46, 0xec, 0xad, 0xe8, 0x0e, 0xb8,
	0x88, 0xaa, 0xdf, 0x11, 0xe4, 0xa7, 0xc5, 0xb2, 0x2f, 0x90, 0x49, 0xed, 0x07, 0x25, 0x1d, 0x8f,
	0xe8, 0xb2, 0x37, 0xff, 0xe3, 0x47, 0x7b, 0xad, 0xfd, 0x30, 0xe2, 0x49, 0xca, 0x18, 0x5c, 0xec,
	0x8e, 0x7d, 0xcf, 0x57, 0x75, 0xd4, 0xe4, 0x48, 0x71, 0x35, 0x42, 0x42, 0x55, 0x61, 0x7c, 0xf2,
	0x88, 0x0c, 0x2f, 0x70, 0x82, 0x30, 0xa2, 0x1d, 0x94, 0x19, 0x94, 0x1f, 0x49, 0x96, 0xe0, 0xc2,
	0xec, 0x05, 0x14, 0xc6, 0xca, 0x41, 0x78, 0x65, 0x34, 0x8f, 0xe9, 0xf0, 0x6f, 0x22, 0x98, 0xe5,
	0xa4, 0xf7, 0xbd, 0xfc, 0xd1, 0xab, 0x6e, 0x32, 0xab, 0xc4, 0xc7, 0xa9, 0xea, 0x2d, 0x24, 0x64,
	0x70, 0xf8, 0x2c, 0x76, 0x90, 0x3b, 0xf5, 0x40, 0x6f, 0x97, 0x38, 0x53, 0xe8, 0x77, 0x2b, 0xbc,
	0xa0, 0x87, 0x4b, 0xa4, 0xb8, 0xfa, 0x00, 0xe9, 0xe4, 0x1b, 0xe3, 0x90, 0x75, 0xc6, 0x8e, 0xfa,
	0x78, 0x47, 0xb2, 0x04, 0x4f, 0x18, 0x9a, 0xd6, 0x66, 0x2b, 0xe9, 0xfb, 0xae, 0xc8, 0xcc, 0x85,
	0xab, 0x6b, 0xc8, 0xe6, 0x5d, 0x87, 0x89, 0x95, 0xde, 0xca, 0x87, 0x59, 0x3e, 0x41, 0x78, 0xf4,
	0x36, 0x18, 0xba, 0xa2, 0x35, 0x50, 0xcc, 0x9e, 0x42, 0xec, 0xc5, 0x9e, 0x66, 0x2c, 0x31, 0x84,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x86, 0xc3, 0x08, 0x86, 0x51, 0x03, 0x00, 0x00,
}
